# ruby's load is nicely explained here:
# https://medium.com/@connorstack/understanding-ruby-load-require-gems-bundler-and-rails-autoloading-from-the-bottom-up-3b422902ca0
common_vagrantfile = "../Vagrantfile.common"
load common_vagrantfile if File.exists?(common_vagrantfile)

